#pragma once
#include <string>
using namespace std;

class QueryUtility {
	
public:
	QueryUtility();
	enum ClauseType {
		CLAUSETYPE_MODIFIES,
		CLAUSETYPE_USES,
		CLAUSETYPE_FOLLOWS,
		CLAUSETYPE_FOLLOWS_STAR,
		CLAUSETYPE_PARENT,
		CLAUSETYPE_PARENT_STAR,
		CLAUSETYPE_CALLS,
		CLAUSETYPE_CALLS_STAR,
		CLAUSETYPE_NEXT,
		CLAUSETYPE_NEXT_STAR,
		CLAUSETYPE_AFFECTS,
		CLAUSETYPE_AFFECTS_STAR,

		CLAUSETYPE_PATTERN_ASSIGN,
		CLAUSETYPE_PATTERN_IF,
		CLAUSETYPE_PATTERN_WHILE,

		CLAUSETYPE_WITH,

		CLAUSETYPE_NULL
	};
	enum SynonymType {
		SYNONYM_TYPE_ASSIGN,
		SYNONYM_TYPE_BOOLEAN,//not design entity 
		SYNONYM_TYPE_CALL,
		SYNONYM_TYPE_CONSTANT,
		SYNONYM_TYPE_IF,
		SYNONYM_TYPE_PROCEDURE,
		SYNONYM_TYPE_PROG_LINE,
		SYNONYM_TYPE_STMT,
		SYNONYM_TYPE_VARIABLE,
		SYNONYM_TYPE_WHILE,
		SYNONYM_TYPE_STMTLST,

		SYNONYM_TYPE_NULL
	};
	public :
		static SynonymType getSynonymType(string type);
		static string getString(SynonymType type);
};