#pragma once


class QueryUtility {
	
public:
	QueryUtility();
	enum ClauseType {
		CLAUSETYPE_MODIFIES,
		CLAUSETYPE_USES,
		CLAUSETYPE_FOLLOWS,
		CLAUSETYPE_FOLLOWS_STAR,
		CLAUSETYPE_PARENT,
		CLAUSETYPE_PARENT_STAR,
		CLAUSETYPE_CALLS,
		CLAUSETYPE_CALLS_STAR,
		CLAUSETYPE_NEXT,
		CLAUSETYPE_NEXT_STAR,
		CLAUSETYPE_AFFECTS,
		CLAUSETYPE_AFFECTS_STAR,

		CLAUSETYPE_PATTERN_ASSIGN,
		CLAUSETYPE_PATTERN_IF,
		CLAUSETYPE_PATTERN_WHILE,

		CLAUSETYPE_WITH,

		CLAUSETYPE_NULL
	};
	
	
};